// GENERATED by scripts/export_engine_data.py — do not edit.
// Source of truth is core/balance_config.py. Re-run the exporter after
// any calibration change, or the website will keep predicting with the
// numbers it was built with.

export const BOTTLENECK_BLEND_K = 4.0 as const;
export const CPU_MS_CONST = 2.25 as const;
export const CPU_PERF_EXPONENT = 1.0 as const;
export const DEFAULT_QUALITY_TIER = "High" as const;
export const DEFAULT_UPSCALING_PASS_COST_MS = 0.35 as const;
export const FG_GPU_OVERHEAD = {
    "2x": 0.35,
    "3x": 0.53,
    "4x": 0.71,
  } as const;
export const FG_OUTPUT_MULTIPLIER = {
    "2x": 2.0,
    "3x": 3.0,
    "4x": 4.0,
  } as const;
export const FG_VRAM_ADD_GB = {
    "2x": 1.0,
    "3x": 1.4,
    "4x": 1.8,
  } as const;
export const GPU_MS_CONST = 2.65 as const;
export const GPU_PERF_EXPONENT = 1.85 as const;
export const OS_RAM_RESERVE_GB = 3.5 as const;
export const PT_CPU_COST_MULT = 1.12 as const;
export const PT_GPU_COST_MULT = 2.98 as const;
export const PT_VRAM_ADD_GB = 1.9 as const;
export const QUALITY_ORDER = ["Very Low", "Low", "Medium", "High", "Ultra", "Extreme"] as const;
export const QUALITY_TIERS = {
    "Very Low": [0.42, 0.8, 0.55],
    "Low": [0.58, 0.86, 0.68],
    "Medium": [0.77, 0.93, 0.83],
    "High": [1.0, 1.0, 1.0],
    "Ultra": [1.34, 1.07, 1.2],
    "Extreme": [1.7, 1.14, 1.38],
  } as const;
export const RAM_ABUNDANCE_BONUS = 1.02 as const;
export const RAM_SHORTFALL_PENALTY = 0.55 as const;
export const RAM_SPILL_COMFORT_RATIO = 4.0 as const;
export const RAM_SPILL_CRAMPED_PENALTY = 0.62 as const;
export const RAM_UNPLAYABLE_SHORTFALL_RATIO = 0.25 as const;
export const REF_SCORE = 100.0 as const;
export const RESOLUTION_PIXELS = {
    "1080p": 1.0,
    "1440p": 1.78,
    "4k": 4.0,
    "8k": 16.0,
  } as const;
export const RES_PIXEL_EXPONENT = 0.82 as const;
export const RES_VRAM_FACTOR = {
    "1080p": 1.0,
    "1440p": 1.14,
    "4k": 1.38,
    "8k": 1.85,
  } as const;
export const RT_CPU_COST_MULT = 1.08 as const;
export const RT_GPU_COST_MULT = 1.62 as const;
export const RT_VRAM_ADD_GB = 1.1 as const;
export const UPSCALING_PASS_COST_MS = {
    "dlss": 0.35,
    "fsr": 0.3,
    "xess": 0.55,
    "dlaa": 0.45,
  } as const;
export const UPSCALING_RENDER_SCALE = {
    "ultra performance": 0.333,
    "performance": 0.5,
    "balanced": 0.58,
    "quality": 0.667,
    "dlaa": 1.0,
    "native": 1.0,
  } as const;
export const UPSCALING_UNSCALED_FRACTION = 0.16 as const;
export const VRAM_ALLOC_APPETITE = 1.12 as const;
export const VRAM_ALLOC_CAPACITY_LIMIT = 0.92 as const;
export const VRAM_ALLOC_HEADROOM_GB = 0.8 as const;
export const VRAM_SPILL_FLOOR = 0.8 as const;
export const VRAM_SPILL_SEVERITY = 0.5 as const;
export const VRAM_TIGHT_HEADROOM_GB = 0.4 as const;
export const VRAM_TIGHT_PENALTY = 0.94 as const;

export function qualityMultipliers(tier: string): readonly [number, number, number] {
  return (QUALITY_TIERS as Record<string, readonly [number, number, number]>)[tier]
    ?? (QUALITY_TIERS as Record<string, readonly [number, number, number]>)[DEFAULT_QUALITY_TIER];
}

export const FG_SUPPORT = {
    "RTX 5090": ["2x", "3x", "4x"],
    "RTX 5080": ["2x", "3x", "4x"],
    "RTX 5070 Ti": ["2x", "3x", "4x"],
    "RTX 5070": ["2x", "3x", "4x"],
    "RTX 5060 Ti": ["2x", "3x"],
    "RTX 5060": ["2x", "3x"],
    "RTX 5050": ["2x"],
    "RTX 4090": ["2x"],
    "RTX 4080": ["2x"],
    "RTX 4070 Ti": ["2x"],
    "RTX 4070": ["2x"],
    "RTX 4060 Ti": ["2x"],
    "RTX 4060": ["2x"],
    "RTX 4050": ["2x"],
    "RX 9070": ["2x"],
    "RX 9060": ["2x"],
    "RX 8900": ["2x"],
    "RX 8800": ["2x"],
    "RX 8700": ["2x"],
    "RX 7900": ["2x"],
    "RX 7800": ["2x"],
    "RX 7700": ["2x"],
    "RX 7600": ["2x"],
    "Arc B580": ["2x"],
    "Arc B570": ["2x"],
  } as const;
