"""
Exports the engine's constants and catalogue for the browser build.

The web frontend runs its own copy of Cadence in TypeScript so that a
prediction needs no server round trip — see frontend/src/engine/cadence.ts and
the reasoning in that file's header. Two implementations means two ways to
drift, so the split here is deliberate:

    balance_config.py  ->  generated, never edited by hand
    catalogue          ->  generated, never edited by hand
    the model itself   ->  hand-ported, guarded by scripts/conformance_test.py

Anything that is only data gets generated, which removes the entire class of
"someone retuned a constant in Python and the website kept the old number".
What is left is the ~300 lines of actual model logic, and that has a test which
runs both implementations over a grid and fails if any answer differs.

Run from the repo root after any calibration change:

    python scripts/export_engine_data.py
"""
import json
import os
import sqlite3
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from core import balance_config as bc
from core import db_manager
from core import scoring_engine as se

OUT_DIR = os.path.join("frontend", "src", "engine")

# Columns the browser needs. Everything else in the database is either legacy
# or only used by the calibration scripts, and shipping it would just be bytes.
GAME_COLUMNS = [
    "id", "name", "genre", "gpu_cost", "cpu_cost", "vram_base_gb", "ram_base_gb",
    "tier_min", "tier_max", "fps_cap", "supports_rt", "supports_pt",
    "supports_dlss", "supports_fsr", "supports_xess",
    "competitive", "target_fps", "cover_url", "flags_verified",
]
CPU_COLUMNS = ["name", "cores", "threads", "boost_clock", "architecture", "power_score"]
GPU_COLUMNS = ["name", "vram", "architecture", "power_score"]


def ts_value(v, indent=2):
    """Render a Python value as TypeScript source."""
    pad = " " * indent
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return json.dumps(v)
    if isinstance(v, (list, tuple)):
        return "[" + ", ".join(ts_value(x, indent) for x in v) + "]"
    # Sets become sorted arrays: TypeScript has Set, but a generated module is
    # easier to read as a literal, and sorting keeps the diff stable when the
    # set is edited.
    if isinstance(v, (set, frozenset)):
        return "[" + ", ".join(ts_value(x, indent) for x in sorted(v)) + "]"
    if isinstance(v, dict):
        inner = ",\n".join(f"{pad}  {json.dumps(k)}: {ts_value(x, indent + 2)}"
                           for k, x in v.items())
        return "{\n" + inner + f",\n{pad}}}"
    raise TypeError(f"cannot render {type(v)}")


def export_balance():
    names = [n for n in dir(bc) if n.isupper() and not n.startswith("_")]
    lines = [
        "// GENERATED by scripts/export_engine_data.py — do not edit.",
        "// Source of truth is core/balance_config.py. Re-run the exporter after",
        "// any calibration change, or the website will keep predicting with the",
        "// numbers it was built with.",
        "",
    ]
    for n in sorted(names):
        value = getattr(bc, n)
        lines.append(f"export const {n} = {ts_value(value)} as const;")
    lines.append("")
    lines.append("export function qualityMultipliers(tier: string): "
                 "readonly [number, number, number] {")
    lines.append("  return (QUALITY_TIERS as Record<string, readonly [number, number, number]>)[tier]")
    lines.append("    ?? (QUALITY_TIERS as Record<string, readonly [number, number, number]>)[DEFAULT_QUALITY_TIER];")
    lines.append("}")
    lines.append("")

    # FG_SUPPORT lives in scoring_engine rather than balance_config, but it is
    # data all the same, so it is generated too.
    lines.append("export const FG_SUPPORT = "
                 + ts_value({k: list(v) for k, v in se.FG_SUPPORT.items()})
                 + " as const;")
    lines.append("")

    path = os.path.join(OUT_DIR, "balance.generated.ts")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    return path, len(names)


def export_catalog():
    conn = db_manager.get_connection()
    conn.row_factory = sqlite3.Row

    def rows(table, columns):
        out = []
        for r in conn.execute(f"SELECT * FROM {table}"):
            keys = set(r.keys())
            out.append({c: r[c] for c in columns if c in keys})
        return out

    # How many benchmark rows stand behind each game. This is the difference
    # between a row the interface can state with confidence and one it should
    # hedge: measured games sit at 8.9% mean error, and the derived costs the
    # rest carry were 49.2% out when tested against the same measurements.
    # Presenting both in the same weight would be dishonest, so the count ships
    # with the catalogue and the UI marks the difference.
    measured = {r["game"]: r["n"] for r in conn.execute(
        "SELECT game, COUNT(*) AS n FROM benchmarks GROUP BY game")}

    games = rows("games", GAME_COLUMNS)
    for g in games:
        g["measurements"] = measured.get(g["name"], 0)

    data = {
        "cpus": rows("cpus", CPU_COLUMNS),
        "gpus": rows("gpus", GPU_COLUMNS),
        "games": games,
    }
    conn.close()

    path = os.path.join(OUT_DIR, "catalog.generated.json")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
    return path, data


def main():
    os.makedirs(OUT_DIR, exist_ok=True)

    bal_path, n_const = export_balance()
    print(f"  {bal_path}   {n_const} sabit")

    cat_path, data = export_catalog()
    size = os.path.getsize(cat_path) / 1024
    print(f"  {cat_path}   {len(data['cpus'])} CPU, {len(data['gpus'])} GPU, "
          f"{len(data['games'])} oyun, {size:.0f} KB")
    print()
    print("  Kalibrasyon degistiginde bunu yeniden calistirin, sonra")
    print("  python scripts/conformance_test.py ile iki motorun ayni sonucu")
    print("  verdigini dogrulayin.")


if __name__ == "__main__":
    main()
