"""
Exports the engine's constants and catalogue for the browser build.

The web frontend runs its own copy of Cadence in TypeScript so that a
prediction needs no server round trip — see frontend/src/engine/cadence.ts and
the reasoning in that file's header. Two implementations means two ways to
drift, so the split here is deliberate:

    balance_config.py  ->  generated, never edited by hand
    catalogue          ->  generated, never edited by hand
    the model itself   ->  hand-ported, guarded by scripts/conformance_test.py

Anything that is only data gets generated, which removes the entire class of
"someone retuned a constant in Python and the website kept the old number".
What is left is the ~300 lines of actual model logic, and that has a test which
runs both implementations over a grid and fails if any answer differs.

Run from the repo root after any calibration change:

    python scripts/export_engine_data.py
"""
import json
import os
import sqlite3
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from core import balance_config as bc
from core import db_manager
from core import scoring_engine as se

OUT_DIR = os.path.join("frontend", "src", "engine")

# Columns the browser needs. Everything else in the database is either legacy
# or only used by the calibration scripts, and shipping it would just be bytes.
# A column the engine reads and this list omits is a fix that never ships. The
# conformance test cannot catch it, because it builds its cases straight from
# the database rather than from what gets exported — so both engines agree
# perfectly on data the site never receives. `rt_gpu_mult` spent its first day
# exactly there: Hitman's measured 2.92 was in the database, honoured by both
# implementations, and absent from the catalogue the browser loads, so every
# page view used the global 1.70.
GAME_COLUMNS = [
    "id", "name", "genre", "gpu_cost", "cpu_cost", "vram_base_gb", "ram_base_gb",
    "tier_min", "tier_max", "fps_cap", "fps_low_ratio", "fps_low_measured",
    "rt_gpu_mult", "gpu_measured", "supports_rt", "supports_pt",
    "supports_dlss", "supports_fsr", "supports_xess",
    "competitive", "target_fps", "cover_url", "flags_verified",
]
CPU_COLUMNS = ["name", "cores", "threads", "boost_clock", "architecture",
               "power_score", "form_factor"]
GPU_COLUMNS = ["name", "vram", "architecture", "power_score", "form_factor"]


def ts_value(v, indent=2):
    """Render a Python value as TypeScript source."""
    pad = " " * indent
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return json.dumps(v)
    if isinstance(v, (list, tuple)):
        return "[" + ", ".join(ts_value(x, indent) for x in v) + "]"
    # Sets become sorted arrays: TypeScript has Set, but a generated module is
    # easier to read as a literal, and sorting keeps the diff stable when the
    # set is edited.
    if isinstance(v, (set, frozenset)):
        return "[" + ", ".join(ts_value(x, indent) for x in sorted(v)) + "]"
    if isinstance(v, dict):
        inner = ",\n".join(f"{pad}  {json.dumps(k)}: {ts_value(x, indent + 2)}"
                           for k, x in v.items())
        return "{\n" + inner + f",\n{pad}}}"
    raise TypeError(f"cannot render {type(v)}")


def export_balance():
    names = [n for n in dir(bc) if n.isupper() and not n.startswith("_")]
    lines = [
        "// GENERATED by scripts/export_engine_data.py — do not edit.",
        "// Source of truth is core/balance_config.py. Re-run the exporter after",
        "// any calibration change, or the website will keep predicting with the",
        "// numbers it was built with.",
        "",
    ]
    for n in sorted(names):
        value = getattr(bc, n)
        lines.append(f"export const {n} = {ts_value(value)} as const;")
    lines.append("")
    lines.append("export function qualityMultipliers(tier: string): "
                 "readonly [number, number, number] {")
    lines.append("  return (QUALITY_TIERS as Record<string, readonly [number, number, number]>)[tier]")
    lines.append("    ?? (QUALITY_TIERS as Record<string, readonly [number, number, number]>)[DEFAULT_QUALITY_TIER];")
    lines.append("}")
    lines.append("")

    # FG_SUPPORT lives in scoring_engine rather than balance_config, but it is
    # data all the same, so it is generated too.
    lines.append("export const FG_SUPPORT = "
                 + ts_value({k: list(v) for k, v in se.FG_SUPPORT.items()})
                 + " as const;")
    lines.append("")

    path = os.path.join(OUT_DIR, "balance.generated.ts")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    return path, len(names)


def engine_stats(conn):
    """The accuracy figures the interface quotes, measured at export time.

    They used to be typed into the interface by hand, and every one of them
    went stale: the footer claimed 106 measurements at 9.0% error long after
    the set had grown past 570, and the note under an unmeasured game quoted
    9% and 49% after both had moved. A number written by hand is a claim about
    the day it was written. Computing it here ties it to the same data the
    catalogue ships with, so the two cannot disagree.

    Two figures, measured two ways, because they answer different questions:

      fitted_error_pct    mean error per row over the benchmark rows the fit
                          uses — the headline accuracy on measured games
      derived_error_pct   leave-one-game-out: every measured game in turn has
                          its profile thrown away and re-derived the way an
                          unmeasured game's is, then scored against its own
                          rows. Averaged per game, alongside measured_error_pct
                          on the same per-game basis so the pair is comparable.
    """
    import statistics
    from migrate_game_profiles import (BLEND_K, DEFAULT_CPU_RATIO,
                                       GENRE_CPU_RATIO, _solve_cpu_gpu_ratio)

    games = {g["name"]: dict(g) for g in db_manager.get_all_games()}
    cpus = {c["name"]: c for c in db_manager.get_all_cpus()}
    gpus = {g["name"]: g for g in db_manager.get_all_gpus()}
    fitted = [dict(r) for r in conn.execute(
        "SELECT * FROM benchmarks WHERE COALESCE(scene,'benchmark')='benchmark'"
        " AND COALESCE(texture_pack,0)=0 AND COALESCE(ray_reconstruction,0)=0")]

    def err(row, game):
        p = se.estimate_fps(
            cpus[row["cpu"]], gpus[row["gpu"]], game, row["resolution"],
            row["settings"], row["upscaling"], row["frame_gen"], row["ram_gb"],
            ray_tracing=bool(row["ray_tracing"]),
            path_tracing=bool(row["path_tracing"]))
        return abs(p - row["fps_avg"]) / row["fps_avg"] * 100

    def derived(g):
        r1 = g["res_1080p_scaling"] or 1.0
        n4 = (g["res_4k_scaling"] or 0.25) / r1
        total = (g["difficulty_multiplier"] or 1.0) / r1
        prior = GENRE_CPU_RATIO.get(g["genre"], DEFAULT_CPU_RATIO)
        w = 0.85 if n4 <= 0.27 else 0.70
        ratio = _solve_cpu_gpu_ratio(n4) * (1 - w) + prior * w
        gpu = total / ((ratio ** BLEND_K + 1.0) ** (1.0 / BLEND_K))
        out = dict(g)
        out.update(gpu_cost=gpu, cpu_cost=gpu * ratio, rt_gpu_mult=None)
        return out

    per_row, meas_g, der_g = [], [], []
    for name in sorted({r["game"] for r in fitted}):
        rs = [r for r in fitted if r["game"] == name]
        e_fit = [err(r, games[name]) for r in rs]
        per_row += e_fit
        meas_g.append(statistics.mean(e_fit))
        d = derived(games[name])
        der_g.append(statistics.mean(err(r, d) for r in rs))

    total_rows = conn.execute("SELECT COUNT(*) FROM benchmarks").fetchone()[0]
    return {
        "measurements": total_rows,
        "fitted_rows": len(per_row),
        "fitted_error_pct": round(statistics.mean(per_row), 1),
        "measured_games": len(meas_g),
        "measured_error_pct": round(statistics.mean(meas_g), 1),
        "derived_error_pct": round(statistics.mean(der_g), 1),
    }


def export_catalog():
    conn = db_manager.get_connection()
    conn.row_factory = sqlite3.Row

    def rows(table, columns):
        out = []
        for r in conn.execute(f"SELECT * FROM {table}"):
            keys = set(r.keys())
            out.append({c: r[c] for c in columns if c in keys})
        return out

    # How many benchmark rows stand behind each game. This is the difference
    # between a row the interface can state with confidence and one it should
    # hedge, so the count ships with the catalogue and the UI marks it.
    measured = {r["game"]: r["n"] for r in conn.execute(
        "SELECT game, COUNT(*) AS n FROM benchmarks GROUP BY game")}

    games = rows("games", GAME_COLUMNS)
    for g in games:
        g["measurements"] = measured.get(g["name"], 0)

    data = {
        "cpus": rows("cpus", CPU_COLUMNS),
        "gpus": rows("gpus", GPU_COLUMNS),
        "games": games,
        "stats": engine_stats(conn),
    }
    conn.close()

    path = os.path.join(OUT_DIR, "catalog.generated.json")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
    return path, data


def main():
    os.makedirs(OUT_DIR, exist_ok=True)

    bal_path, n_const = export_balance()
    print(f"  {bal_path}   {n_const} sabit")

    cat_path, data = export_catalog()
    size = os.path.getsize(cat_path) / 1024
    print(f"  {cat_path}   {len(data['cpus'])} CPU, {len(data['gpus'])} GPU, "
          f"{len(data['games'])} oyun, {size:.0f} KB")
    print()
    print("  Kalibrasyon degistiginde bunu yeniden calistirin, sonra")
    print("  python scripts/conformance_test.py ile iki motorun ayni sonucu")
    print("  verdigini dogrulayin.")


if __name__ == "__main__":
    main()
